### ISSUE TITLE
Compatibility issues with AutoReconnectReforged

### ISSUE THREAD

**Issue by Makev1ch** [MrMasrozYTLIVE/CatTeleportMod-Fabric#1]
https://mclo.gs/xEAq7CN

**Comment by MrMasrozYTLIVE** [comment]
Я так предполагаю что дело в AutoReconnect моде

**Comment by Makev1ch** [comment]
Да действительно дело в AutoReconnect, но даже с ним через команду все работает нормально

**Comment by MrMasrozYTLIVE** [comment]
> Да действительно дело в AutoReconnect, но даже с ним через команду все работает нормально

Потому что команда не открывала (по какой то причине) меню выхода с сервера. Я уже поговорил с автором AutoReconnect, в течении пары дней он добавит API для отмены переподключения и я буду вручную отменять реконнект если он происходит от телепортации

**Comment by MrMasrozYTLIVE** [comment]
@Makev1ch Исправлено в 1.2.6
